steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
    '--build-arg', 'NODE_ENV=production',
    '-t', 'gcr.io/$PROJECT_ID/gtest:$COMMIT_SHA', '.']
  # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gtest:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'gtest'
    - '--image'
    - 'gcr.io/$PROJECT_ID/gtest:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'